import 'package:flutter/material.dart';

class AppColors {
  AppColors._();
  static const Color tealBackground = Color(0xFF4FB6AD);
  static const Color primaryColor = Color(0xFF4A52DA);
  static const Color goldColor = Color(0xFFFFD700);
  static const Color softBlue = Color(0xFFF4F6FF);
  static const Color softMint = Color(0xFFEAF8F4);
  static const Color borderSoft = Color(0xFFE7EBF3);
  static const Color ratingGold = Color(0xFFFFC857);
  static const Color onlineIndicator = Color(0xFF18A957);
  static const Color subtitleText = Color(0xFF6E7787);
  static const Color white = Colors.white;
  static const Color black = Colors.black;
  static const Color grey = Colors.grey;
  static const Color green = Colors.green;
  static const Color textGrey = Colors.grey;
  static const Color favIcon = Color(0xFFE53935);
  static const Color chatIcon = Color(0xFF1E88E5);
  static const Color blockedIcon = Color(0xFF546E7A);
  static const Color termsIcon = Color(0xFFFFB300);
  static const Color contactIcon = Color(0xFF43A047);
  static const Color profileIcon = Color(0xFFFFB74D);
  static const Color red = Colors.red;
  static const Color actionBlue = Color(0xFF1E88E5);
  static const Color aboutIcon = Color(0xFF2196F3);
  static const Color onCall = Color(0xFFFFB74D);
  static const Color callBackground = Color(0xFFFFEBEB);
  static const Color callStatusText = Color(0xFF16884F);
  static const Color callEndedStatus = Color(0xFFE53935);
  static const Color callBreathingGlow = Color(0xFF20B15A);
  static const Color callBreathingGlowSoft = Color(0xFFC7F6D9);
  static const Color callControlSurface = Color(0xCCFFFFFF);
  static const Color callMutedIcon = Color(0xB3000000);
  static const Color lightGrey = Color(0xFFEEEEEE);
  static const Color transparent = Colors.transparent;
  static const Color orange = Colors.orange;
  static const Color amber = Colors.amber;
  static const Color warningBackground = Color(0xFFFFF8E1);
}
